build: off

image: Visual Studio 2015

platform:
  - x86
  - x64

skip_tags: true

cache:
  - node_modules -> package.json

environment:
  matrix:
  - nodejs_version: "12"

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm install npm -g
  - npm install
  - npm install -g istanbul

test_script:
  - node --version
  - npm --version
  - istanbul cover .\node_modules\mocha\bin\_mocha

after_test:
  - bash <(curl -s https://codecov.io/bash)
